### ISSUE TITLE
Can't import Newtonsoft.Json .zip into NT8

### ISSUE THREAD

**Issue by lepete11** [westsider/Indicators#1]
Is there anything you know about how to import the current Newtonsoft.json into NT8.   An error message in NT8 states that the namespace is for an older version of NT, which has to be 7?

**Comment by westsider** [comment]
Good Question, I remember I did that in NT7 and it was complicated, I don't remember the exact details but it involved... copy the dependency to the NT7 folder, then include it in the ninjascript file as an import at the top of the file. Sorry, I don't recall exact instructions.

**Comment by lepete11** [comment]
Warren, you're exactly right. Just reference the dll for .net .45 in NT8,
and works perfectly.  Thx, L

Probably delete this issue?

**Comment by westsider** [comment]
Very good, glad that was the solution, I'll close the issue.
